version: "3.8"

services: 
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: supreme
      POSTGRES_PASSWORD: fishstick
      POSTGRES_DB: sf_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: