// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/dataFrame.proto

package dataframe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MockDataFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          string                 `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockDataFrame) Reset() {
	*x = MockDataFrame{}
	mi := &file_proto_dataFrame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockDataFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockDataFrame) ProtoMessage() {}

func (x *MockDataFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataFrame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockDataFrame.ProtoReflect.Descriptor instead.
func (*MockDataFrame) Descriptor() ([]byte, []int) {
	return file_proto_dataFrame_proto_rawDescGZIP(), []int{0}
}

func (x *MockDataFrame) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MockDataFrame) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MockDataFrame) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MockDataFrame) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MockDataFrame) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *MockDataFrame) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_proto_dataFrame_proto protoreflect.FileDescriptor

const file_proto_dataFrame_proto_rawDesc = "" +
	"\n" +
	"\x15proto/dataFrame.proto\x12\tDataFrame\"\x97\x01\n" +
	"\rMockDataFrame\x12\x1c\n" +
	"\tmessageId\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04Data\x18\x06 \x01(\tR\x04DataB\x13Z\x11./proto;dataframeb\x06proto3"

var (
	file_proto_dataFrame_proto_rawDescOnce sync.Once
	file_proto_dataFrame_proto_rawDescData []byte
)

func file_proto_dataFrame_proto_rawDescGZIP() []byte {
	file_proto_dataFrame_proto_rawDescOnce.Do(func() {
		file_proto_dataFrame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dataFrame_proto_rawDesc), len(file_proto_dataFrame_proto_rawDesc)))
	})
	return file_proto_dataFrame_proto_rawDescData
}

var file_proto_dataFrame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_dataFrame_proto_goTypes = []any{
	(*MockDataFrame)(nil), // 0: DataFrame.MockDataFrame
}
var file_proto_dataFrame_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dataFrame_proto_init() }
func file_proto_dataFrame_proto_init() {
	if File_proto_dataFrame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dataFrame_proto_rawDesc), len(file_proto_dataFrame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dataFrame_proto_goTypes,
		DependencyIndexes: file_proto_dataFrame_proto_depIdxs,
		MessageInfos:      file_proto_dataFrame_proto_msgTypes,
	}.Build()
	File_proto_dataFrame_proto = out.File
	file_proto_dataFrame_proto_goTypes = nil
	file_proto_dataFrame_proto_depIdxs = nil
}
