// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/UserAuthFrame.proto

package dataframe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is the frame that registers a client
type CLIENT_AUTH_REQUEST_FRAME struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UniqueClientId string                 `protobuf:"bytes,1,opt,name=uniqueClientId,proto3" json:"uniqueClientId,omitempty"` // unique identifier for the client from the client
	Secret         string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`                 // secret for authentication works like auth
	StreamId       int32                  `protobuf:"varint,4,opt,name=streamId,proto3" json:"streamId,omitempty"`            // stream identifier
	IsNewClient    bool                   `protobuf:"varint,3,opt,name=IsNewClient,proto3" json:"IsNewClient,omitempty"`      // true if new client, false if existing client
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CLIENT_AUTH_REQUEST_FRAME) Reset() {
	*x = CLIENT_AUTH_REQUEST_FRAME{}
	mi := &file_proto_UserAuthFrame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLIENT_AUTH_REQUEST_FRAME) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLIENT_AUTH_REQUEST_FRAME) ProtoMessage() {}

func (x *CLIENT_AUTH_REQUEST_FRAME) ProtoReflect() protoreflect.Message {
	mi := &file_proto_UserAuthFrame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLIENT_AUTH_REQUEST_FRAME.ProtoReflect.Descriptor instead.
func (*CLIENT_AUTH_REQUEST_FRAME) Descriptor() ([]byte, []int) {
	return file_proto_UserAuthFrame_proto_rawDescGZIP(), []int{0}
}

func (x *CLIENT_AUTH_REQUEST_FRAME) GetUniqueClientId() string {
	if x != nil {
		return x.UniqueClientId
	}
	return ""
}

func (x *CLIENT_AUTH_REQUEST_FRAME) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *CLIENT_AUTH_REQUEST_FRAME) GetStreamId() int32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *CLIENT_AUTH_REQUEST_FRAME) GetIsNewClient() bool {
	if x != nil {
		return x.IsNewClient
	}
	return false
}

// This is the frame that the server sends to the client after successful authentication
type CLIENT_AUTH_RESPONSE_FRAME struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SfClientId    string                 `protobuf:"bytes,1,opt,name=sfClientId,proto3" json:"sfClientId,omitempty"` // id assigned by server...it is like a domain id  clientID@domain
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`           // token for authentication
	StreamId      int32                  `protobuf:"varint,4,opt,name=streamId,proto3" json:"streamId,omitempty"`    // stream identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLIENT_AUTH_RESPONSE_FRAME) Reset() {
	*x = CLIENT_AUTH_RESPONSE_FRAME{}
	mi := &file_proto_UserAuthFrame_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLIENT_AUTH_RESPONSE_FRAME) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLIENT_AUTH_RESPONSE_FRAME) ProtoMessage() {}

func (x *CLIENT_AUTH_RESPONSE_FRAME) ProtoReflect() protoreflect.Message {
	mi := &file_proto_UserAuthFrame_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLIENT_AUTH_RESPONSE_FRAME.ProtoReflect.Descriptor instead.
func (*CLIENT_AUTH_RESPONSE_FRAME) Descriptor() ([]byte, []int) {
	return file_proto_UserAuthFrame_proto_rawDescGZIP(), []int{1}
}

func (x *CLIENT_AUTH_RESPONSE_FRAME) GetSfClientId() string {
	if x != nil {
		return x.SfClientId
	}
	return ""
}

func (x *CLIENT_AUTH_RESPONSE_FRAME) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CLIENT_AUTH_RESPONSE_FRAME) GetStreamId() int32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

var File_proto_UserAuthFrame_proto protoreflect.FileDescriptor

const file_proto_UserAuthFrame_proto_rawDesc = "" +
	"\n" +
	"\x19proto/UserAuthFrame.proto\x12\tDataFrame\"\x99\x01\n" +
	"\x19CLIENT_AUTH_REQUEST_FRAME\x12&\n" +
	"\x0euniqueClientId\x18\x01 \x01(\tR\x0euniqueClientId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x1a\n" +
	"\bstreamId\x18\x04 \x01(\x05R\bstreamId\x12 \n" +
	"\vIsNewClient\x18\x03 \x01(\bR\vIsNewClient\"n\n" +
	"\x1aCLIENT_AUTH_RESPONSE_FRAME\x12\x1e\n" +
	"\n" +
	"sfClientId\x18\x01 \x01(\tR\n" +
	"sfClientId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\bstreamId\x18\x04 \x01(\x05R\bstreamIdB\x13Z\x11./proto;dataframeb\x06proto3"

var (
	file_proto_UserAuthFrame_proto_rawDescOnce sync.Once
	file_proto_UserAuthFrame_proto_rawDescData []byte
)

func file_proto_UserAuthFrame_proto_rawDescGZIP() []byte {
	file_proto_UserAuthFrame_proto_rawDescOnce.Do(func() {
		file_proto_UserAuthFrame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_UserAuthFrame_proto_rawDesc), len(file_proto_UserAuthFrame_proto_rawDesc)))
	})
	return file_proto_UserAuthFrame_proto_rawDescData
}

var file_proto_UserAuthFrame_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_UserAuthFrame_proto_goTypes = []any{
	(*CLIENT_AUTH_REQUEST_FRAME)(nil),  // 0: DataFrame.CLIENT_AUTH_REQUEST_FRAME
	(*CLIENT_AUTH_RESPONSE_FRAME)(nil), // 1: DataFrame.CLIENT_AUTH_RESPONSE_FRAME
}
var file_proto_UserAuthFrame_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_UserAuthFrame_proto_init() }
func file_proto_UserAuthFrame_proto_init() {
	if File_proto_UserAuthFrame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_UserAuthFrame_proto_rawDesc), len(file_proto_UserAuthFrame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_UserAuthFrame_proto_goTypes,
		DependencyIndexes: file_proto_UserAuthFrame_proto_depIdxs,
		MessageInfos:      file_proto_UserAuthFrame_proto_msgTypes,
	}.Build()
	File_proto_UserAuthFrame_proto = out.File
	file_proto_UserAuthFrame_proto_goTypes = nil
	file_proto_UserAuthFrame_proto_depIdxs = nil
}
